# Generated by Django 4.0 on 2022-09-15 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pageid', models.IntegerField(blank=True, null=True, verbose_name='Страница - номер')),
                ('pageparid', models.IntegerField(blank=True, null=True, verbose_name='Группа страницы')),
                ('pagename', models.CharField(blank=True, max_length=255, null=True, verbose_name='название и URL страницы')),
                ('menuname', models.CharField(blank=True, max_length=50, null=True, verbose_name='меню')),
                ('pagetitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title страницы')),
                ('pagekeywords', models.CharField(blank=True, max_length=650, null=True, verbose_name='keywords страницы')),
                ('pagedescription', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Метатег description страницы')),
                ('pagecontent', models.TextField(blank=True, null=True, verbose_name='Контент страницы')),
                ('sort', models.IntegerField(blank=True, null=True, verbose_name='сортировка')),
                ('pageimg', models.CharField(blank=True, max_length=255, null=True, verbose_name='URL страницы')),
            ],
            options={
                'verbose_name': 'Контентные страницы',
                'verbose_name_plural': 'основные страницы',
            },
        ),
    ]
