# Generated by Django 4.0 on 2022-09-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naviway', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Texniki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_texnik', models.IntegerField(blank=True, null=True, verbose_name='Техника - номер')),
                ('name', models.CharField(blank=True, max_length=81, null=True, verbose_name='Наме техники')),
                ('anotacia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Анотация')),
                ('texnika', models.TextField(blank=True, null=True, verbose_name='Контент страницы')),
                ('koment_spec', models.CharField(blank=True, max_length=810, null=True, verbose_name='Комментарий специалиста')),
                ('id_podxod', models.IntegerField(blank=True, null=True, verbose_name='принадлежность техники')),
                ('istochnik', models.CharField(blank=True, max_length=100, null=True, verbose_name='Авторство техники')),
                ('sex', models.CharField(blank=True, max_length=20, null=True, verbose_name='Ограничения по полу')),
                ('kol_people', models.CharField(blank=True, max_length=20, null=True, verbose_name='Нужно людей')),
                ('age', models.CharField(blank=True, max_length=50, null=True, verbose_name='возрастные ограничения')),
            ],
            options={
                'verbose_name': 'Техники',
                'verbose_name_plural': 'Техники',
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ('menuname',), 'verbose_name': 'Контентные страницы', 'verbose_name_plural': 'основные страницы'},
        ),
        migrations.AlterField(
            model_name='page',
            name='menuname',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='меню'),
        ),
    ]
