# Generated by Django 4.0 on 2022-09-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naviway', '0004_cursce_cursceteh_podhod_alter_targ_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Targetteh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_texnik', models.IntegerField(blank=True, null=True, verbose_name='Техника - номер')),
                ('id_cel', models.IntegerField(blank=True, null=True, verbose_name='цель техники')),
            ],
            options={
                'verbose_name': 'Цели распределение',
                'verbose_name_plural': 'Цели распределение',
            },
        ),
    ]
